services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_DB=journalblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres

  backend-fastapi:
    build: .
    image: backend-fastapi
    container_name: backend-fastapi
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=journalblog
    links:
      - "postgres:loaclhost"
    networks:
      - dbnet
    ports:
      - "127.0.0.1:8000:4000"
    volumes:
      - ${PWD}:/app
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
