services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    restart:
      always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    # links:
    #   - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres

  backend-fastapi:
    build: .
    image: backend-fastapi
    container_name: backend-fastapi
    env_file:
      - .env
    # links:
    #   - "postgres:localhost"
    networks:
      - dbnet
    restart:
      always
    command: "uvicorn main:app --host 0.0.0.0 --port 4000 --reload" # --workers 4
    ports:
      - "127.0.0.1:8000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
